name: Run Tests

on:
  push:
    branches:
      - '**' # This will trigger the action on push to any branch
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: Run tests
        run: go test -v ./...
